name: drishti_fasal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  csv: ^5.0.0

  cupertino_icons: ^1.0.8

  # ✅ Image + ML
  image_picker: ^1.0.7
  tflite_flutter: ^0.12.1
  image: ^4.1.7

  # ✅ Weather + API
  flutter_dotenv: ^5.1.0
  geolocator: ^10.1.0
  http: ^1.2.0

  # UI
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/drishtifasal_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/models/hybrid_model_float32.tflite
    - assets/images/
    - assets/data/crop_stage_disease_mapping.csv